### PR TITLE
Add support for installation with opam pin

### PR DESCRIPTION
**Pull request by imbsky**
We can now install and try reanalyze using the following way:

```
opam pin add reanalyze https://github.com/cristianoc/reanalyze.git
opam install reanalyze
```

### CODE REVIEW

**Comment by cristianoc** [comment]
I had these Azure issues earlier already, with no relevant changes.
Let's see if it gets resolved.

**Comment by cristianoc** [comment]
Actually, this is a different issue now (before it was not cheking out the repo), and could be related to the PR.

**Comment by cristianoc** [comment]
@imbsky how does one test it locally?
```
opam pin add .
```

gives me

```
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[ERROR] The compilation of reanalyze failed at "/Users/cristianoc/.opam/opam-init/hooks/sandbox.sh build dune
        subst".

#=== ERROR while compiling reanalyze.~dev =====================================#
# context     2.0.3 | macos/x86_64 | ocaml-base-compiler.4.06.1 | pinned(git+file:///Users/cristianoc/reasonml/reanalyze#imbsky-support-opam-pin#a4cf7e73)
# path        ~/.opam/4.06.1/.opam-switch/build/reanalyze.~dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune subst
# exit-code   1
# env-file    ~/.opam/log/reanalyze-61671-865888.env
# output-file ~/.opam/log/reanalyze-61671-865888.out
### output ###
# Error: The project name is not defined, please add a (name <name>) field to
# your dune-project file.
```

**Comment by imbsky** [comment]
It should work with the last commit, but the build will fail, so opam can't pin it.

**Comment by cristianoc** [comment]
There are a bunch of useful changes here. Merging.
If more needs to be done for opam, how about a separate PR.
E.g. how does the build fail and why.

**Comment by imbsky** [comment]
I get an error like the one below, but I haven't read much of the project code, so I don't know immediately why this is happening.

```
File "examples/_unknown_", line 1, characters 0-0:
Error: File unavailable: examples/DeadCodePPX.exe
```

**Comment by cristianoc** [comment]
These are symbolic links used by the project, and that dune does not like, and that esy populates.
I want to get around that anyway.

**Comment by cristianoc** [comment]
@imbsky I'll take care of that:
https://github.com/cristianoc/reanalyze/issues/44

**Pull request merged**
