### PR TITLE
Using OCaml standard Location format on .ml and .mli files

### PR DESCRIPTION
**Pull request by jberdine**

### CODE REVIEW

**Comment by cristianoc** [comment]
Thanks!

**Comment by cristianoc** [comment]
@jberdine looks like `Location.print_loc` always prints excape sequences, even when the output is redirected. Do you know if this can be turned off programmatically? Not a big deal either way.

https://github.com/cristianoc/reanalyze/commit/4f608c26d9ff0ecf620a54aceaf2d4075c6b8881

**Comment by jberdine** [comment]
Hmm, that's suboptimal. Maybe `Misc.Color.setup (Some Never)` is in compilerlibs and can be called.

**Comment by cristianoc** [comment]
That does the trick. Thanks!

**Pull request merged**
