### PR TITLE
Fix symlink to deadcodeppx.exe

### PR DESCRIPTION
**Pull request by imbsky**
Closes: #44

### CODE REVIEW

**Comment by imbsky** [comment]
This does not exist.
`_esy/default/build/install/default/bin/DeadCodePPX.exe`
https://github.com/cristianoc/reanalyze/blob/master/dead-code-ppx/dune

**Comment by imbsky** [comment]
This avoids the following errors when building with dune:

```
λ dune build
File "examples/_unknown_", line 1, characters 0-0:
Error: File unavailable: examples/DeadCodePPX.exe
```

**Comment by imbsky** [comment]
But we still can't install this in an opam environment with sandboxing enabled. This is because there are some symlinks in the repository.

**Comment by cristianoc** [comment]
Looks like a clear step forward. Can I merge?

**Comment by imbsky** [comment]
Yes, this can be merged.

**Comment by imbsky** [comment]
But note that we still can't install reanalyze using opam with this change. I plan to open a PR to make that possible.

**Comment by cristianoc** [comment]
Merging this first step.

**Pull request merged**
