### PR TITLE
Better handling of paths for ids, with finer granularity of implementations vs interfaces.

### PR DESCRIPTION
**Pull request by cristianoc**
Move towards paths of the form [+]M.[+]x
To indicate whether M is an implementation or not, and whether value x is in an interfaace.

### CODE REVIEW

**Comment by cristianoc** [comment]
Next steps  for https://github.com/cristianoc/reanalyze/issues/5:

This explicit example:
```ocaml
module M
 : sig
  type t = A of int | B of int
end
=
struct
  (* module T = struct type t = A of int | B of int end
  include T *)
  type t = A of int | B of int
end
```

gives
```sh
  addTypeDeclaration A A.ml:3:11 path:+A.M.t
  addTypeDeclaration B A.ml:3:20 path:+A.M.t
  addTypeDeclaration +A A.ml:9:11 path:+A.M.+t
  addTypeDeclaration +B A.ml:9:20 path:+A.M.+t
  extendTypeDependencies A.ml:9:11 --> A.ml:3:11
  extendTypeDependencies A.ml:3:11 --> A.ml:9:11
  extendTypeDependencies A.ml:9:20 --> A.ml:3:20
  extendTypeDependencies A.ml:3:20 --> A.ml:9:20
  addTypeReference A.ml:9:20 --> A.ml:3:20
  addTypeReference A.ml:3:20 --> A.ml:9:20
  addTypeReference A.ml:9:11 --> A.ml:3:11
  addTypeReference A.ml:3:11 --> A.ml:9:11
```

while the example with include:
```ocaml
module M
 : sig
  type t = A of int | B of int
end
=
struct
  module T = struct type t = A of int | B of int end
  include T
  (* type t = A of int | B of int *)
end

```

gives:
```sh
  addTypeDeclaration A A.ml:3:11 path:+A.M.t
  addTypeDeclaration B A.ml:3:20 path:+A.M.t
  addTypeDeclaration +A A.ml:7:29 path:+A.M.T.+t
  addTypeDeclaration +B A.ml:7:38 path:+A.M.T.+t
```

**Comment by cristianoc** [comment]
@jberdine this is now a legit starting point ^^^

I'd like to understand the `include` example a little better. In particular the extent of such examples.
Trying to avoid replicating the entire type checker mechanism, yet give useful results.
This include example is now on the fence.

**Comment by jberdine** [comment]
This seems to help a lot on my code, thanks! I seem some cases like https://github.com/cristianoc/reanalyze/issues/12 that don't seem to be about `include` but maybe related.

**Comment by cristianoc** [comment]
Thanks for https://github.com/cristianoc/reanalyze/issues/12 . I'll merge the changes so far and take a look at that before thinking further about include.

**Pull request merged**
