### PR TITLE
Unbreak reason-vscode extension

### PR DESCRIPTION
**Pull request by cristianoc**
The reason-vscode extension does not work anymore if `@opam/dune": "2.0.1"` is selected.

### CODE REVIEW

**Comment by cristianoc** [comment]
FYI: @imbsky only noticed now that updating dune beyond a certain version breaks the extension.

**Comment by imbsky** [comment]
Have you tried this extension?
https://github.com/ocamllabs/vscode-ocaml-platform
This is probably better than that extension.

**Comment by cristianoc** [comment]
Yes  I have, and it's too early.
Some files are all green.
It does not build.

**Comment by cristianoc** [comment]
I'm actually pretty interested in the new extension and I am monitoring it closely.

**Comment by imbsky** [comment]
Does green mean that syntax highlighting doesn't work?

**Comment by cristianoc** [comment]
Yes sorry, syntax highlighting is not there yet.

**Comment by imbsky** [comment]
The next version, 0.5.0, has many improvements. If you want to try it out, you can choose the latest build from here, download artifact and install it manually.
https://github.com/ocamllabs/vscode-ocaml-platform/actions
https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/CHANGELOG.md

**Pull request merged**
